Project wizard is now with .kateproject file generation

diff --git a/bin/mktsimple b/bin/mktsimple
--- a/bin/mktsimple
+++ b/bin/mktsimple
@@ -35,6 +35,7 @@ OPTIONS:
 	                                 If header and source files are placed in the source directories, enter an empty string or a single space.
 	                                 This option may be repeated. The default value is 'include'
 	--hello-world                  : Create a hello world project.
+	-k|--kate-project              : Create a kate project.
 	-o|--overwrite                 : Overwrite (and backup) existing files in project destination.
 	-n|--no-prompt|--noprompt      : Do not enter the interactive mode and use the command line options only.
 	--mkts-install-dir VALUE       : The base directory of the mktsimple installation. The default
@@ -52,12 +53,12 @@ readonly mkts='mktsimple'
 readonly valid_types='otocpp ipbcpp opbc opbcpp opb'
 readonly all_install_files='in_place_cpp.mk in_place_cpp.mk out_place_c.mk out_place_cpp.mk out_place_cpp.mk'
 pr3=(
-     'opbc   -- C project     Out Place Build'$'\n''    Build one executable from all %.c source files in all project source directories.'$'\n'
-     'opbcpp -- C++ project   Out Place Build'$'\n''    Build one executable from all %.cpp and %.cc source files in all project source directories.'$'\n'
-     'opb    -- C/C++ project Out Place Build'$'\n''    Build one executable from all C++, C and assembler source files in all project source directories.'$'\n'
-     'ipbcpp -- C++ project   In Place Build'$'\n''    Build one executable from all %.cpp and %.cc source files in the project directory.'$'\n'
-     'otocpp -- C++ project   One To One'$'\n''    Build executable targets from each %.cpp and %.cc source file in the project directory.'$'\n'
-     'exit'
+	'opbc   -- C project     Out Place Build'$'\n''    Build one executable from all %.c source files in all project source directories.'$'\n'
+	'opbcpp -- C++ project   Out Place Build'$'\n''    Build one executable from all %.cpp and %.cc source files in all project source directories.'$'\n'
+	'opb    -- C/C++ project Out Place Build'$'\n''    Build one executable from all C++, C and assembler source files in all project source directories.'$'\n'
+	'ipbcpp -- C++ project   In Place Build'$'\n''    Build one executable from all %.cpp and %.cc source files in the project directory.'$'\n'
+	'otocpp -- C++ project   One To One'$'\n''    Build executable targets from each %.cpp and %.cc source file in the project directory.'$'\n'
+	'exit'
 )
 readonly pr3
 
@@ -182,6 +183,7 @@ target_name=
 src_dir=
 inc_dir=
 hello_world=
+kateproject=
 copy_warn=
 overwrite=
 
@@ -258,6 +260,8 @@ while [[ $# -gt 0 ]]; do
 		fi;;
 	'--hello-world')
 		hello_world='true';;
+	'-k'|'--kate-project')
+		kateproject='true';;
 	'-o'|'--overwrite')
 		overwrite='true';;
 	'-n'|'--no-prompt'|'--noprompt')
@@ -307,10 +311,11 @@ else
 		mkts_install_dir="${my_install_dir}"
 	fi
 fi
+
 if ! check_install_dir "${mkts_install_dir}" >&2; then
 	exit 2
 fi
-
+mkts_install_dir="${mkts_install_dir%/}"
 # request project directory
 if [[ -z ${no_prompt} ]]; then
 	read_value "Enter the project directory" 'project_dir' 'project1' 'check_project_dir'
@@ -400,8 +405,13 @@ if [[ -z "${no_prompt}" && -z "${copy_warn}" ]]; then
 fi
 
 # request hello world
-if [[ -z "${no_prompt}" ]]; then
+if [[ -z "${no_prompt}" && -z "${hello_world}" ]]; then
 	read_yes_no "Create a hello world project?" 'hello_world'
+fi
+
+# request kateproject
+if [[ -z "${no_prompt}" && -z "${kateproject}" ]]; then
+	read_yes_no "Create a Kate project file?" 'kateproject'
 fi
 
 # check src dir and project type
@@ -451,16 +461,21 @@ makefile_name="${project_dir}/Makefile"
 warndir_name="${project_dir}/${mkts}"
 project_mk_name="${project_dir}/project.mk"
 project_mk_temp_name="${project_dir}/.project.mk"
+kateproject_name="${project_dir}/.kateproject"
+kateproject_temp_name="${project_dir}/kateproject.tmp"
+
 overwrite_makefile=
 overwrite_project_mk=
 overwrite_module=
 overwrite_warn_dir=
+overwrite_kateproject=
 overwrite_necessary=
 [[ -a "${makefile_name}" ]] && overwrite_makefile='true'
 [[ -n "${project_mk_required}" && -a "${project_mk_name}" ]] && overwrite_project_mk='true'
 [[ -n "${hello_world}" && -a "${module_name}" ]] && overwrite_module='true'
 [[ -n "${copy_warn}" && -d "${warndir_name}" ]] && overwrite_warn_dir='true'
-[[ -n ${overwrite_makefile} || -n ${overwrite_project_mk} || -n ${overwrite_module} || -n ${overwrite_warn_dir} ]] && overwrite_necessary='true'
+[[ -n "${kateproject}" && -a "${kateproject_name}" ]] && overwrite_kateproject='true'
+[[ -n ${overwrite_makefile} || -n ${overwrite_project_mk} || -n ${overwrite_module} || -n ${overwrite_warn_dir} || -n ${overwrite_kateproject} ]] && overwrite_necessary='true'
 if [[ -z "${no_prompt}" ]]; then
 	if [[ -n ${overwrite_necessary} ]]; then
 		read_yes_no "Some files already exists. Overwite?" 'overwrite'
@@ -471,6 +486,7 @@ if [[ -z ${overwrite} && -n ${overwrite_necessary} ]]; then
 	[[ -n "${overwrite_project_mk}" ]] && echo "ERROR: Projectfile ${project_mk_name} already exists" >&2
 	[[ -n "${overwrite_module}" ]] && echo "ERROR: Project modul ${module_name} already exists" >&2
 	[[ -n "${overwrite_warn_dir}" ]] && echo "ERROR: Warnings ${warndir_name} already exists" >&2
+	[[ -n "${overwrite_kateproject}" ]] && echo "ERROR: kateproject file ${kateproject_name} already exists" >&2
 	exit 1
 fi
 
@@ -501,6 +517,7 @@ if [[ -n ${out_place_project_type} ]]; then
 fi
 [[ -n "${hello_world}" ]] && echo "Create hello world program module ${module_name}"
 [[ -n "${copy_warn}" ]] && echo "Copy warnings into project directory."
+[[ -n "${kateproject}" ]] && echo "Create a Kate project file ${kateproject_name}"
 temp='no'
 [[ -n ${overwrite} ]] && temp='yes'
 echo "Overwrite and backup existing files: $temp"
@@ -509,6 +526,7 @@ echo "Overwrite and backup existing files: $temp"
 [[ -n "${overwrite_project_mk}" ]] && echo "Backup project file ${project_mk_name} !"
 [[ -n "${overwrite_module}" ]] && echo "Backup modul ${module_name} !"
 [[ -n "${overwrite_warn_dir}" ]] && echo "Overwrite warnings in dir ${warndir_name} !"
+[[ -n "${overwrite_kateproject}" ]] && echo "Overwrite kate project file ${kateproject_name} !"
 echo '**********************************************************************************'
 execute_all=
 if [[ -z "${no_prompt}" ]]; then
@@ -582,6 +600,74 @@ if [[ -n ${execute_all} ]]; then
 	if [[ -n "${copy_warn}" ]]; then
 		mkdir -pv "${warndir_name}" || abort_func
 		cp -v --no-dereference "${mkts_install_dir}/include/${mkts}/"* "${warndir_name}" || abort_func
+	fi
+
+	# kateproject
+	if [[ -n "${kateproject}" ]]; then
+		invocation_opt=
+		if [[ "${mkts_install_dir}" != '/usr/local' && -z "${copy_warn}" ]]; then
+			invocation_opt="-I ${mkts_install_dir}/include "
+		fi
+		case ${pr_type} in
+		otocpp)
+			 targetstr=$'\t\t\t{\n\t\t\t\t"name": "debug",\n\t\t\t\t"build_cmd": "make '"${invocation_opt}"$'all"\n\t\t\t},\n'
+			targetstr+=$'\t\t\t{\n\t\t\t\t"name": "run",\n\t\t\t\t"build_cmd": "make '"${invocation_opt}"$'BUILD_MODE=run all"\n\t\t\t},';;
+		ipbcpp)
+			 targetstr=$'\t\t\t{\n\t\t\t\t"name": "debug",\n\t\t\t\t"build_cmd": "make '"${invocation_opt}"$'all",\n\t\t\t\t"run_cmd": "./'"${target_name}"$'"\n\t\t\t},\n'
+			targetstr+=$'\t\t\t{\n\t\t\t\t"name": "run",\n\t\t\t\t"build_cmd": "make '"${invocation_opt}"$'BUILD_MODE=run all",\n\t\t\t\t"run_cmd": "./'"${target_name}"$'"\n\t\t\t},';;
+		*)
+			 targetstr=$'\t\t\t{\n\t\t\t\t"name": "debug",\n\t\t\t\t"build_cmd": "make '"${invocation_opt}"$'all",\n\t\t\t\t"run_cmd": "./debug/'"${target_name}"$'"\n\t\t\t},\n'
+			targetstr+=$'\t\t\t{\n\t\t\t\t"name": "run",\n\t\t\t\t"build_cmd": "make '"${invocation_opt}"$'BUILD_MODE=run all",\n\t\t\t\t"run_cmd": "./run/'"${target_name}"$'"\n\t\t\t},';;
+	esac
+		cat >> "${kateproject_temp_name}" <<EOF
+{
+	"name": "${defaul_target_name}",
+	"files": [
+		{ "directory": ".", "hidden": 0 }
+	],
+	"exclude_patterns" : [
+		"^debug/build/.*",
+		"^run/build/.*",
+		"*.mks.tmp",
+		"compile_commands.json",
+		"*.~*"
+	],
+	"build": {
+		"directory": ".",
+		"build": "make all",
+		"clean": "make clean",
+		"install": "make install",
+		"targets": [
+${targetstr}
+			{
+				"name": "clean",
+				"build_cmd": "make ${invocation_opt}clean"
+			},
+			{
+				"name": "Increment warning level",
+				"build_cmd": "make ${invocation_opt}inc_warn_level"
+			},
+			{
+				"name": "Decrement warning level",
+				"build_cmd": "make ${invocation_opt}dec_warn_level"
+			},
+			{
+				"name": "purge",
+				"build_cmd": "make ${invocation_opt}purge"
+			},
+			{
+				"name": "Project Info",
+				"build_cmd": "make ${invocation_opt}show"
+			},
+			{
+				"name": "Help",
+				"build_cmd": "make ${invocation_opt}help"
+			}
+		]
+	}
+}
+EOF
+		mv -v --backup=numbered "${kateproject_temp_name}" "${kateproject_name}" || abort_func
 	fi
 
 	echo "**** All done ****"
