Corrections in project wizard

diff --git a/bin/mktsimple b/bin/mktsimple
--- a/bin/mktsimple
+++ b/bin/mktsimple
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
 
+# guess the base directory of the mkts installation
 my_install_dir=
 my_command="${0##*/}"
 if [[ "$0" == /* ]]; then
@@ -13,31 +14,51 @@ else
 fi
 
 usage() {
-	cat <<-EOF
-		The Make It Simple project wizard - generate the makefile.
-		Usage: ${my_command} [option..]
+	cat <<EOF
 
-		OPTIONS:
-		-h|--help                      : Display this help.
-		--help=type                    : Print project type information.
-		-p|--project-dir VALUE         : The base directory of the C/C++ project.
-		-t|--type|--project-type VALUE : The type of the project. Valid types are: otocpp, ipbcpp, opbcpp, opbc, opb.
-		                                 To find out more about the types use option --help=type
-		-c|--copy-warn                 : Make a local copy of the warning.mk files in the project directory.
-		--target-name VALUE            : Name of the executable to build. Default value is the last path component of
-		                                 of the project directory.
-		-s|--src|--src-dir VALUE       : Directory with the c/c++ source files. If the source files are located in more
-		                                 than one directory, this option may be repeated. Default: src
-		-i|--inc|--include-dir VALUE   : The project internal include directory for the quote form of the include directive (-iquote).
-		                                 Omit this variable, if header and source files are placed in the source directories.
-		                                 This option may be repeated. The default value is 'include'
-		--hello-world                  : Create a hello world project.
-		-o|--overwrite                 : Overwrite (and backup) existing files in project destination.
-		-n|--no-prompt|--noprompt      : Do not enter the interactive mode and use the command line options only.
-		--mkts-install-dir VALUE       : The base directory of the mktsimple installation. The default
-		                                 value is detected from the location of the ${my_command} script.
-	EOF
+The Make It Simple project wizard - generate the makefile.
+
+Usage: ${my_command} [option..]
+
+OPTIONS:
+	-h|--help                      : Display this help.
+	--help=type                    : Print project type information.
+	-p|--project-dir VALUE         : The base directory of the C/C++ project.
+	-y|--type|--project-type VALUE : The type of the project. Valid types are: otocpp, ipbcpp, opbcpp, opbc, opb.
+	                                 To find out more about the types use option --help=type
+	-c|--copy-warn                 : Make a local copy of the warning.mk files in the project directory.
+	-t|--target-name VALUE         : Name of the executable to build. Default value is the last path component of
+	                                 of the project directory.
+	-s|--src|--src-dir VALUE       : Directory with the c/c++ source files. If the source files are located in more
+	                                 than one directory, this option may be repeated. Default: src
+	-i|--inc|--include-dir VALUE   : The project internal include directory for the quote form of the include directive (-iquote).
+	                                 Omit this variable, if header and source files are placed in the source directories.
+	                                 This option may be repeated. The default value is 'include'
+	--hello-world                  : Create a hello world project.
+	-o|--overwrite                 : Overwrite (and backup) existing files in project destination.
+	-n|--no-prompt|--noprompt      : Do not enter the interactive mode and use the command line options only.
+	--mkts-install-dir VALUE       : The base directory of the mktsimple installation. The default
+	                                 value is detected from the location of the ${my_command} script.
+
+RETURNS:
+	0    : Success
+	1    : Runtime error
+	2    : Wrong invokation
+	3    : User abort
+EOF
 }
+
+readonly mkts='mktsimple'
+readonly valid_types='otocpp ipbcpp opbc opbcpp opb'
+readonly all_install_files='in_place_cpp.mk in_place_cpp.mk out_place_c.mk out_place_cpp.mk out_place_cpp.mk'
+pr3=('otocpp -- C++ project   One To One'$'\n''    Build executable targets from each %.cpp and %.cc source file in the project directory.'$'\n'
+     'ipbcpp -- C++ project   In Place Build'$'\n''    Build one executable from all %.cpp and %.cc source files in the project directory.'$'\n'
+     'opbcpp -- C++ project   Out Place Build'$'\n''    Build one executable from all %.cpp and %.cc source files in all project source directories.'$'\n'
+     'opbc   -- C project     Out Place Build'$'\n''    Build one executable from all %.c source files in all project source directories.'$'\n'
+     'opb    -- C/C++ project Out Place Build'$'\n''    Build one executable from all C++, C and assembler source files in all project source directories.'$'\n'
+     'exit'
+)
+readonly pr3
 
 # check whether directory $1 contains valid install files
 check_install_dir() {
@@ -81,7 +102,7 @@ check_type() {
 		exit 1
 	fi
 	local x
-	local is_valid=''
+	local is_valid=
 	for x in $valid_types; do
 		if [[ "$1" == "$x" ]]; then
 			is_valid='true'
@@ -103,13 +124,13 @@ abort_func() {
 
 # read yes/no form stdin
 # $1 - Prompt
-# $2 - name of the output
+# $2 - name of in/output
 # start over when the referenced value is not empty
 read_yes_no() {
 	local temp
 	declare -ln ref=$2
 	while [[ -z ${ref} ]]; do
-		read -r -p "$1 (^D to exit) [y/n] " || exit 1
+		read -r -p "$1 (^D to exit) [y/n] " || exit 3
 		temp="${REPLY,,}"
 		if [[ (${temp} == 'yes') || (${temp} == 'y') ]]; then
 			ref='true'
@@ -121,17 +142,19 @@ read_yes_no() {
 			ref=
 		fi
 	done
-	}
+	echo
+}
 
 # read a value from stdin
 # $1 - Prompt
-# $2 - name of the output
-# $3 - default
+# $2 - name of in/output
+# $3 - default value
 # $4 - validator (evaluated)
+# start over when the referenced value is not empty
 read_value() {
 	declare -ln ref=$2
 	while [[ -z ${ref} ]]; do
-		read -r -p "$1 (^D to exit) [${3}] " || exit 1
+		read -r -p "$1 (^D to exit) [${3}] " || exit 3
 		if [[ -z ${REPLY} ]]; then
 			ref="${3}"
 			break
@@ -143,19 +166,8 @@ read_value() {
 			ref=
 		fi
 	done
+	echo
 }
-
-readonly valid_types='otocpp ipbcpp opbc opbcpp opb'
-readonly mkts='mktsimple'
-readonly all_install_files='in_place_cpp.mk in_place_cpp.mk out_place_c.mk out_place_cpp.mk out_place_cpp.mk'
-pr3=('otocpp -- C++ project   One To One      - Build executable targets from each %.cpp and %.cc source file in the project directory.'
-     'ipbcpp -- C++ project   In Place Build  - Build one executable from all %.cpp and %.cc source files in the project directory.'
-     'opbcpp -- C++ project   Out Place Build - Build one executable from all %.cpp and %.cc source files in all project source directories.'
-     'opbc   -- C project     Out Place Build - Build one executable from all %.c source files in all project source directories.'
-     'opb    -- C/C++ project Out Place Build - Build one executable from all C++, C and assembler source files in all project source directories.'
-     'exit'
-)
-readonly pr3
 
 invalid_parameter=
 missing_value=
@@ -196,7 +208,7 @@ while [[ $# -gt 0 ]]; do
 			missing_value='true'
 			break
 		fi;;
-	'-t'|'--type'|'--project-type')
+	'-y'|'--type'|'--project-type')
 		if [[ $# -gt 1 ]]; then
 			one_more_shift='true'
 			pr_type="$2"
@@ -206,7 +218,7 @@ while [[ $# -gt 0 ]]; do
 		fi;;
 	'-c'|'--copy-warn')
 		copy_warn='true';;
-	'--target-name')
+	'-t'|'--target-name')
 		if [[ $# -gt 1 ]]; then
 			one_more_shift='true'
 			target_name="$2"
@@ -253,11 +265,13 @@ while [[ $# -gt 0 ]]; do
 done
 
 if [[ -n $invalid_parameter ]]; then
-	echo "ERROR: Invalid parameter $1" >&2
+	echo -e "\nERROR: Invalid parameter $1\n" >&2
+	usage >&2
 	exit 2
 fi
 if [[ -n $missing_value ]]; then
-	echo "ERROR: Missing value for parameter $1" >&2
+	echo -e "\nERROR: Missing value for parameter $1\n" >&2
+	usage >&2
 	exit 2
 fi
 
@@ -267,7 +281,9 @@ fi
 if [[ -n ${typehelprequest} ]]; then
 	declare -i i
 	for ((i=0; i<${#pr3[*]}; i++)); do
-		echo "${pr3[$i]}"
+		if [[ "${pr3[$i]}" != exit* ]]; then
+			echo "${pr3[$i]}"
+		fi
 	done
 fi
 if [[ -n ${helprequest} || -n ${typehelprequest} ]]; then
@@ -276,19 +292,9 @@ fi
 
 echo -e "\nMake It Simple installation in: ${my_install_dir}\n"
 
-# request project directory
-if [[ -z ${no_prompt} ]]; then
-	read_value "Enter the project directory" 'project_dir' 'project1' 'check_project_dir'
-	echo
-fi
-if ! check_project_dir >&2 "${project_dir}"; then
-	exit 1
-fi
-
 # request and validate mkts installation directory
 if [[ -z ${no_prompt} ]]; then
 	read_value "Enter the base directory of the ${mkts} installation."$'\n' 'mkts_install_dir' "${my_install_dir}" 'check_install_dir'
-	echo
 else
 	# lookup for an installation
 	if [[ -z ${mkts_install_dir} ]]; then
@@ -296,7 +302,15 @@ else
 	fi
 fi
 if ! check_install_dir "${mkts_install_dir}" >&2; then
-	exit 1
+	exit 2
+fi
+
+# request project directory
+if [[ -z ${no_prompt} ]]; then
+	read_value "Enter the project directory" 'project_dir' 'project1' 'check_project_dir'
+fi
+if ! check_project_dir >&2 "${project_dir}"; then
+	exit 2
 fi
 
 # request and validate the type of the installation
@@ -310,23 +324,19 @@ if [[ -z ${no_prompt} ]]; then
 					pr_type="${x%%\ *}"
 					break;;
 				6)
-					exit 1;;
+					exit 3;;
 			esac
-		done || exit 1
+		done || exit 3
 	fi
 	echo
 fi
 if ! check_type "$pr_type" >&2; then
-	exit 1
+	exit 2
 fi
+out_place_project_type=
+[[ ${pr_type} == opb* ]] && out_place_project_type='true'
 
-# request copy warnings local option
-if [[ -z "${no_prompt}" && -z "${copy_warn}" ]]; then
-	read_yes_no "Make a local copy of the warning files in the project directory?" 'copy_warn'
-	echo
-fi
-
-# request target name
+# request target name - check target name
 if [[ ${project_dir} == '.' ]]; then
 	temp="${PWD}"
 else
@@ -340,15 +350,30 @@ if [[ -z "${no_prompt}" ]]; then
 		target_name=
 	else
 		read_value "Name of the executable to build?" 'target_name' "${defaul_target_name}" 'true'
-		echo
+	fi
+else
+	if [[ "${pr_type}" == oto* ]]; then
+		target_name=
+	else
+		[[ -z ${target_name} ]] && target_name="${defaul_target_name}"
+	fi
+fi
+if [[ "${pr_type}" == oto* ]]; then
+	if [[ -n ${target_name} ]]; then
+		echo "ERROR: No target name allowed in One To One project type" >&2
+		exit 2
+	fi
+else
+	if [[ -z ${target_name} ]]; then
+		echo "ERROR: No target name!" >&2
+		exit 2
 	fi
 fi
 
-if [[ ($pr_type != 'otocpp') && ($pr_type != 'ipbcpp') ]]; then
+if [[ -n ${out_place_project_type} ]]; then
 	# request source dir list
 	if [[ -z "${no_prompt}" ]]; then
 		read_value "Enter a space separated source directory list." 'src_dir' 'src' 'true'
-		echo
 	else
 		[[ -z ${src_dir} ]] && src_dir='src'
 	fi
@@ -356,39 +381,46 @@ if [[ ($pr_type != 'otocpp') && ($pr_type != 'ipbcpp') ]]; then
 	# request include dir list
 	if [[ -z "${no_prompt}" ]]; then
 		read_value "Enter a space separated include directory list." 'inc_dir' 'include' 'true'
-		echo
 	else
 		[[ -z ${inc_dir} ]] && inc_dir='include'
 	fi
 fi
-first_src_dir=
-for temp in ${src_dir}; do
-	first_src_dir="${temp}"
-	break
-done
+
+# request copy warnings local option
+if [[ -z "${no_prompt}" && -z "${copy_warn}" ]]; then
+	read_yes_no "Make a local copy of the warning files in the project directory?" 'copy_warn'
+fi
 
 # request hello world
 if [[ -z "${no_prompt}" ]]; then
 	read_yes_no "Create a hello world project?" 'hello_world'
-	echo
 fi
 
 # check src dir and project type
-if [[ (${pr_type} == oto*) || (${pr_type} == ipb*) ]]; then
+if [[ -z ${out_place_project_type} ]]; then
 	if [[ -n $src_dir ]]; then
 		echo "ERROR: Source directory '${src_dir}'specified but project is in place type ${pr_type}" >&2
+		exit 2
 	fi
 	if [[ -n $inc_dir ]]; then
 		echo "ERROR: Include directory '${inc_dir}'specified but project is in place type ${pr_type}" >&2
+		exit 2
 	fi
 	module_name="${project_dir}/hello.c"
 else
 	if [[ -z $src_dir ]]; then
 		echo "ERROR: No source directory specified but project is out place type ${pr_type}" >&2
+		exit 2
 	fi
 	if [[ -z $inc_dir ]]; then
 		echo "ERROR: No include directory specified but project is in place type ${pr_type}" >&2
+		exit 2
 	fi
+	first_src_dir=
+	for temp in ${src_dir}; do
+		first_src_dir="${temp}"
+		break
+	done
 	module_name="${project_dir}/${first_src_dir}/hello.c"
 fi
 if [[ ${pr_type} == *cpp ]]; then
@@ -399,45 +431,36 @@ target_name_required=
 src_dir_required=
 inc_dir_required=
 [[ (${target_name} != "${defaul_target_name}") && (${pr_type} != oto*) ]] && target_name_required='true'
-[[ $src_dir != 'src' ]] && src_dir_required='true'
-[[ $inc_dir != inc* ]] && inc_dir_required='true'
-project_mk_required=
+[[ (-n $out_place_project_type) && ($src_dir != 'src') ]] && src_dir_required='true'
+[[ (-n $out_place_project_type) && ($inc_dir != inc*) ]] && inc_dir_required='true'
+project_mk_required='true'		# if true an existing project.mk is backuped
 [[ -n $target_name_required || -n $src_dir_required || -n $inc_dir_required ]] && project_mk_required='true'
 
 # check if some files already exists
 makefile_name="${project_dir}/Makefile"
 warndir_name="${project_dir}/${mkts}"
 project_mk_name="${project_dir}/project.mk"
+overwrite_makefile=
+overwrite_project_mk=
+overwrite_module=
+overwrite_warn_dir=
 overwrite_necessary=
-[[ -a "${makefile_name}" ]] && overwrite_necessary='true'
-[[ -n "${copy_warn}" && -d "${warndir_name}" ]] && overwrite_necessary='true'
-[[ -n "${project_mk_required}" && -a "${project_mk_name}" ]] && overwrite_necessary='true'
-[[ -n "${hello_world}" && -a "${module_name}" ]] && overwrite_necessary='true'
-
-if [[ -z "${no_prompt}" && -z "${overwrite}" ]]; then
+[[ -a "${makefile_name}" ]] && overwrite_makefile='true'
+[[ -n "${project_mk_required}" && -a "${project_mk_name}" ]] && overwrite_project_mk='true'
+[[ -n "${hello_world}" && -a "${module_name}" ]] && overwrite_module='true'
+[[ -n "${copy_warn}" && -d "${warndir_name}" ]] && overwrite_warn_dir='true'
+[[ -n ${overwrite_makefile} || -n ${overwrite_project_mk} || -n ${overwrite_module} || -n ${overwrite_warn_dir} ]] && overwrite_necessary='true'
+if [[ -z "${no_prompt}" ]]; then
 	if [[ -n ${overwrite_necessary} ]]; then
 		read_yes_no "Some files already exists. Overwite?" 'overwrite'
-		echo
 	fi
 fi
-
-if [[ -z ${overwrite} ]]; then
-	if [[ -a "${makefile_name}" ]]; then
-		echo "ERROR: Makefile ${makefile_name} already exists" >&2
-		exit 1
-	fi
-	if [[ -n "${copy_warn}" && -d "${warndir_name}" ]]; then
-		echo "ERROR: Warnings ${warndir_name} already exists" >&2
-		exit 1
-	fi
-	if [[ -n "${project_mk_required}" && -a "${project_mk_name}" ]]; then
-		echo "ERROR: Projectfile ${project_mk_name} already exists" >&2
-		exit 1
-	fi
-	if [[ -n "${hello_world}" && -a "${module_name}" ]]; then
-		echo "ERROR: Project modul ${module_name} already exists" >&2
-		exit 1
-	fi
+if [[ -z ${overwrite} && -n ${overwrite_necessary} ]]; then
+	[[ -n "${overwrite_makefile}" ]] && echo "ERROR: Makefile ${makefile_name} already exists" >&2
+	[[ -n "${overwrite_project_mk}" ]] && echo "ERROR: Projectfile ${project_mk_name} already exists" >&2
+	[[ -n "${overwrite_module}" ]] && echo "ERROR: Project modul ${module_name} already exists" >&2
+	[[ -n "${overwrite_warn_dir}" ]] && echo "ERROR: Warnings ${warndir_name} already exists" >&2
+	exit 1
 fi
 
 # get the type info string
@@ -452,35 +475,35 @@ for ((i=0; i<${#pr3[*]}; i++)); do
 done
 
 # final summary check
-echo '**********************************************'
+echo '**********************************************************************************'
 echo "Make It Simple installing directory ${mkts_install_dir}"
+echo
 echo "Project directory ${project_dir}"
 echo "Type of the makefile to install ${pr_type}"
-echo "${pr_type_info}"
-if [[ ${pr_type} != 'otocpp' ]]; then
+echo "	${pr_type_info}"
+if [[ ${pr_type} != oto* ]]; then
 	echo "Name of the executable to build: ${target_name}"
 fi
-if [[ ${pr_type} == opb* ]]; then
+if [[ -n ${out_place_project_type} ]]; then
 	echo "Directories with the source files: ${src_dir}"
 	echo "Include directories: ${inc_dir}"
 fi
+[[ -n "${hello_world}" ]] && echo "Create hello world program module ${module_name}"
+[[ -n "${copy_warn}" ]] && echo "Copy warnings into project directory."
 temp='no'
 [[ -n ${overwrite} ]] && temp='yes'
 echo "Overwrite and backup existing files: $temp"
-if [[ -n "${copy_warn}" ]]; then
-	echo "Copy warnings into project directory."
-	if [[ (-d "${warndir_name}") && (-n "${overwrite}") ]]; then
-		echo "Overwrite warndir ${warndir_name} !"
-	fi
-fi
-if [[ -n "${hello_world}" ]]; then
-	echo "Create hello world program module ${module_name}"
-fi
-echo '**********************************************'
+
+[[ -n "${overwrite_makefile}" ]] && echo "Backup makefile ${makefile_name} !"
+[[ -n "${overwrite_project_mk}" ]] && echo "Backup project file ${project_mk_name} !"
+[[ -n "${overwrite_module}" ]] && echo "Backup modul ${module_name} !"
+[[ -n "${overwrite_warn_dir}" ]] && echo "Overwrite warnings in dir ${warndir_name} !"
+echo '**********************************************************************************'
 execute_all=
 if [[ -z "${no_prompt}" ]]; then
 	read_yes_no 'Proceed?' 'execute_all'
-	echo
+else
+	execute_all='true'
 fi
 
 # execution
@@ -505,18 +528,13 @@ if [[ -n ${execute_all} ]]; then
 			src_name='out_place.mk'
 	esac
 	cp -v "${mkts_install_dir}/share/${mkts}/${src_name}" "${makefile_name}" || abort_func
-	# warn directory
-	if [[ -n "${copy_warn}" ]]; then
-		mkdir -pv "${warndir_name}" || abort_func
-		cp -v "${mkts_install_dir}/include/${mkts}/"* "${warndir_name}" || abort_func
-	fi
 	# create dirs
-	if [[ ${pr_type} == opb* ]]; then
+	if [[ -n ${out_place_project_type} ]]; then
 		for temp in ${src_dir}; do
-			mkdir -pv "${project_dir}/${temp}"
+			mkdir -pv "${project_dir}/${temp}" || abort_func
 		done
 		for temp in ${inc_dir}; do
-			mkdir -pv "${project_dir}/${temp}"
+			mkdir -pv "${project_dir}/${temp}" || abort_func
 		done
 	fi
 	# project.mk
@@ -549,6 +567,11 @@ if [[ -n ${execute_all} ]]; then
 			echo -e "#include <stdio.h>\nint main() {\n	printf(\"Hello World !!!\\\\n\");\n	return 0;\n}\n" > "${module_name}" || abort_func
 			echo "Write ${module_name}"
 		fi
+	fi
+	# warn directory
+	if [[ -n "${copy_warn}" ]]; then
+		mkdir -pv "${warndir_name}" || abort_func
+		cp -v --no-dereference "${mkts_install_dir}/include/${mkts}/"* "${warndir_name}" || abort_func
 	fi
 
 	echo "**** All done ****"
